# 0. Import standard packages

In [200]:
import pandas as pd 
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Set-Up of Matrices for Collaborative filtering

First we want to implement the ratings matrix from Table 2.1 featuring 5 users and 6 items. We want to employ a simple user-based and item-based model for imputing ratings. For that we will use the cosine and the pearson-correlation-coefficient.

In [201]:
# create the tables 2.1 and 2.2

table_2_1 = np.array([[7, 6, 7, 4, 5 , 4], [6,7,np.nan, 4,3,4], [np.nan, 3, 3, 1, 1, np.nan], [1, 2, 2 , 3 ,3 , 4], [1, np.nan, 1, 2, 3, 3]])

In [202]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

Next, we want to compute the pearson-correlation-coefficient. The formula for this is:

$ \mu_u = \frac{\sum_{k \in I_{u}} r_{uk}}{|I_{u}|} $

$  Sim(u,v) = Pearson(u,v) = \frac{\sum_{k \in I_{u} \cap I_{v}} (r_{uk}- \mu_{u}) \cdot (r_{uk}- \mu_{u}) }{\sqrt{\sum_{k \in I_{u}\cap I_{v}} (r_{uk}- \mu_{u})^2} \cdot \sqrt{\sum_{k \in I_{u}\cap I_{v}} (r_{vk}- \mu_{v})^2}} $

In [203]:
def pearson_corr(table, x: int, y: int):
    # x and y are the rows of table on which to perform computation
    # get I_x and I_y
    I_x = np.where(np.isnan(table[x]) == False)[0]
    I_y = np.where(np.isnan(table[y]) == False)[0]
    # get the common indices
    I = np.intersect1d(I_x, I_y)
    # get the mean of x and y
    x_mean = np.mean(table[x][I])
    y_mean = np.mean(table[y][I])
    # get the numerator
    numerator = np.sum((table[x][I] - x_mean)*(table[y][I] - y_mean))
    # get the denominator
    denominator = np.sqrt(np.sum((table[x][I] - x_mean)**2)*np.sum((table[y][I] - y_mean)**2))
    # get the correlation
    corr = numerator/denominator
    return corr

Let's compute the correlation coefficient for rows 0 and 2 (1 and 3 in the book). In the book, it is given as 0.894.

In [204]:
pearson_corr(table_2_1, 0, 2)

np.float64(0.8944271909999159)

While we're at it, we can also compute the entire correlation matrix:

In [205]:
# generate a correlation matrix for the table
corr_matrix = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        corr_matrix[i,j] = pearson_corr(table_2_1, i, j)

corr_matrix

array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
       [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
       [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
       [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
       [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]])

Let's write a function that does this:

In [206]:
def corr_matrix_func(table, dimension):
    if dimension == 0:
        number = table.shape[dimension]
        corr_matrix = np.zeros((number, number))
        for i in range(number):
            for j in range(number):
                corr_matrix[i,j] = pearson_corr(table, i, j)
    elif dimension == 1:
        number = table.shape[dimension]
        corr_matrix = np.zeros((number, number))
        table = table.T
        for i in range(number):
            for j in range(number):
                corr_matrix[i,j] = pearson_corr(table, i, j)
    else:
        print("Invalid dimension")
        return None
    return corr_matrix

In [207]:
corr_matrix_func(table = table_2_1, dimension = 0)

array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
       [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
       [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
       [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
       [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]])

In [208]:
corr_matrix_func(table_2_1, 0), corr_matrix_func(table_2_1, 1)

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\2376229201.py:16: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


(array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
        [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
        [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
        [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
        [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]]),
 array([[1.        , 0.94063416, 0.98782916, 0.89714996, 0.67675297,
         0.57263713],
        [0.94063416, 1.        , 0.99862543, 0.69310328, 0.51449576,
                nan],
        [0.98782916, 0.99862543, 1.        , 0.6381449 , 0.62092042,
         0.62861856],
        [0.89714996, 0.69310328, 0.6381449 , 1.        , 0.81348922,
         0.87038828],
        [0.67675297, 0.51449576, 0.62092042, 0.81348922, 1.        ,
         0.33333333],
        [0.57263713,        nan, 0.62861856, 0.87038828, 0.33333333,
         1.        ]]))

This way we can compute the correlation coefficient both for rows or columns.

Next, we can demean the rating in every line.

In [209]:
def demean_func(table):
    # demean the table
    new_table = np.zeros(table.shape)
    for i in range(table.shape[0]):
        I = np.where(np.isnan(table[i]) == False)[0]
        new_table[i][I] = table[i][I] - np.mean(table[i][I])
    return new_table

In [210]:
table_2_2 = demean_func(table_2_1)
table_2_2

array([[ 1.5,  0.5,  1.5, -1.5, -0.5, -1.5],
       [ 1.2,  2.2,  0. , -0.8, -1.8, -0.8],
       [ 0. ,  1. ,  1. , -1. , -1. ,  0. ],
       [-1.5, -0.5, -0.5,  0.5,  0.5,  1.5],
       [-1. ,  0. , -1. ,  0. ,  1. ,  1. ]])

We also want to store the means somewhere. Let us write a function for that.

In [211]:
def mean_compute(table, dimension = 0):
    # compute the mean of the table
    if dimension == 1:
        table_copy = table.T
    else:
        table_copy = table
    mean = np.zeros(table_copy.shape[0])
    for i in range(table_copy.shape[0]):
        I = np.where(np.isnan(table_copy[i]) == False)[0]
        mean[i] = np.mean(table_copy[i][I])
    return mean

user_mean = mean_compute(table_2_1, 0)
user_mean

array([5.5, 4.8, 2. , 2.5, 2. ])

In [212]:
mean_compute(table_2_1, 1)

array([3.75, 4.5 , 3.25, 2.8 , 3.  , 3.75])

We can use the demeaned table to better predict a rating. Suppose that we want to predict for user in 3 (row-index 2) their ratings for movies 1 and 6 (indices 0 and 5, respectively). We can first compute the set of relevant neighbours as those whose correlation exceeds 0.7 (as an arbitrary benchmark).

In [213]:
corr_matrix_table_2_2 = corr_matrix_func(table_2_1, 0)
corr_matrix_table_2_2

array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
       [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
       [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
       [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
       [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]])

Aside from themselves, this is the case for users 1 and 2 (indices 0 and 1):

In [214]:
k = np.where((corr_matrix_table_2_2[2] > 0.7))
k = k[0][:-1]
k

array([0, 1])

In [215]:
# create a deep copy of table_2_2
table_2_1_copy = table_2_1.copy()
table_2_1_copy[2,0] = user_mean[2] + np.sum(corr_matrix_table_2_2[2][k]*table_2_2[k,0])/np.sum(np.abs(corr_matrix_table_2_2[2][k]))
table_2_1_copy

array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        ,        nan, 4.        , 3.        ,
        4.        ],
       [3.34386392, 3.        , 3.        , 1.        , 1.        ,
               nan],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        ,        nan, 1.        , 2.        , 3.        ,
        3.        ]])

Let us encapsulate this in a function. We will have to specify a correlation-threshold to determine k, and then within the function we create a deep-copy that fills in the NaN-values.

In [216]:
def imputation_function(table, threshold, dimension):
    table_copy = table.copy()
    # compute correlation_matrix
    corr_matrix = corr_matrix_func(table, dimension)
    # compute means
    user_mean = mean_compute(table, dimension)
    # demean the table
    table_copy_dm = demean_func(table_copy)
    # for each row in correlation matrix compute the k based on threshold
    k = [[] for _ in range(corr_matrix.shape[0])]
    for i in range(corr_matrix.shape[0]):
        k[i] = np.where((corr_matrix[i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(corr_matrix.shape[0]):
        k[i] = np.setdiff1d(k[i], i)
    # for each row and column in the table, compute the imputation
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            if np.isnan(table[i,j]):
                table_copy[i,j] = user_mean[i] + np.sum(corr_matrix[i][k[i]]*table_copy_dm[k[i],j])/np.sum(np.abs(corr_matrix[i][k[i]]))
    return table_copy, corr_matrix, user_mean, k

In [217]:
table_2_1_imputed, corr_matrix_comp, user_mean_comp, k_comp = imputation_function(table_2_1, 0.7, 0)

In [218]:
table_2_1_imputed

array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        , 6.0135157 , 4.        , 3.        ,
        4.        ],
       [3.34386392, 3.        , 3.        , 1.        , 1.        ,
        0.86431752],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        , 1.5       , 1.        , 2.        , 3.        ,
        3.        ]])

In [219]:
corr_matrix_comp

array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
       [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
       [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
       [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
       [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]])

In [220]:
user_mean_comp

array([5.5, 4.8, 2. , 2.5, 2. ])

In [221]:
k_comp

[array([1, 2]), array([0, 2]), array([0, 1]), array([4]), array([3])]

# Interestingly enough, we can do the entire thing now as well for items!

In [222]:
table_2_1_imputed_cols, corr_matrix_comp_cols, user_mean_comp_cols, k_comp_cols = imputation_function(table_2_1, 0.7, 1)
table_2_1_imputed_cols

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\2376229201.py:16: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        , 5.74252405, 4.        , 3.        ,
        4.        ],
       [4.59918476, 3.        , 3.        , 1.        , 1.        ,
        2.10190223],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        , 2.5       , 1.        , 2.        , 3.        ,
        3.        ]])

In [223]:
corr_matrix_comp_cols

array([[1.        , 0.94063416, 0.98782916, 0.89714996, 0.67675297,
        0.57263713],
       [0.94063416, 1.        , 0.99862543, 0.69310328, 0.51449576,
               nan],
       [0.98782916, 0.99862543, 1.        , 0.6381449 , 0.62092042,
        0.62861856],
       [0.89714996, 0.69310328, 0.6381449 , 1.        , 0.81348922,
        0.87038828],
       [0.67675297, 0.51449576, 0.62092042, 0.81348922, 1.        ,
        0.33333333],
       [0.57263713,        nan, 0.62861856, 0.87038828, 0.33333333,
        1.        ]])

In [224]:
k_comp_cols

[array([1, 2, 3]),
 array([0, 2]),
 array([0, 1]),
 array([0, 4, 5]),
 array([3]),
 array([3])]

#### 2.3.1.1 Similarity Function Variants

We have now computed using the pearson-correlation coefficient. Next up, let's turn towards using the cosine-distance as well as z-scores.

Raw Cosine is computed as:

$  RawCosine(u,v) = \frac{\sum_{k \in I_{u} \cap I_{v}} r_{uk}\cdot r_{uk} }{\sqrt{\sum_{k \in I_{u}\cap I_{v}} r_{uk}^2} \cdot \sqrt{\sum_{k \in I_{u}\cap I_{v}} r_{vk}^2}} $

This considerably simplifies computation. In some implementations, the normalization factors do not constrain on k being in the sets of both users but only one in order to make things feasible:

$  FeasibleRawCosine(u,v) = \frac{\sum_{k \in I_{u} \cap I_{v}} r_{uk}\cdot r_{uk} }{\sqrt{\sum_{k \in I_{u}} r_{uk}^2} \cdot \sqrt{\sum_{k \in I_{v}} r_{vk}^2}} $


In [225]:
def RawCosine(table, x: int, y: int):
    # x and y are the rows of table on which to perform computation
    # get I_x and I_y
    I_x = np.where(np.isnan(table[x]) == False)[0]
    I_y = np.where(np.isnan(table[y]) == False)[0]
    # get the common indices
    I = np.intersect1d(I_x, I_y)
    # get the numerator
    numerator = np.sum(table[x][I]*table[y][I])
    # get the denominator
    denominator = np.sqrt(np.sum(table[x][I]**2)*np.sum(table[y][I]**2))
    # get the correlation
    raw_cosine = numerator/denominator
    return raw_cosine

def FeasibleRawCosine(table, x: int, y: int):
    # x and y are the rows of table on which to perform computation
    # get I_x and I_y
    I_x = np.where(np.isnan(table[x]) == False)[0]
    I_y = np.where(np.isnan(table[y]) == False)[0]
    # get the common indices
    I = np.intersect1d(I_x, I_y)
    # get the numerator
    numerator = np.sum(table[x][I]*table[y][I])
    # get the denominator
    denominator = np.sqrt(np.sum(table[x][I_x]**2)*np.sum(table[y][I_y]**2))
    # get the correlation
    feasible_raw_cosine = numerator/denominator
    return feasible_raw_cosine

In [226]:
RawCosine(table_2_1, 0, 2), FeasibleRawCosine(table_2_1, 0, 2)

(np.float64(0.956182887467515), np.float64(0.7766217620286883))

Often we find the Pearson-Correlation to be the preferrable measure as it provides bias-adjustment due to the mean-centering (comp. p. 37).
Inference is impacted by the number of common ratings, $ | I_u \cap I_v | $ between two users u and v. If two users have only few ratings in common, we might want to downweight the impact that this user-pair has on the final imputation. We can do this via significance weighting:

$ DiscountedSim(u,v) = Sim(u,v) * \frac{ \min\{|I_u \cap I_v|, \beta\}}{\beta} $

In [227]:
def DiscountedSim(table, x: int, y: int, beta: float):
    # x and y are the rows of table on which to perform computation
    # get I_x and I_y
    I_x = np.where(np.isnan(table[x]) == False)[0]
    I_y = np.where(np.isnan(table[y]) == False)[0]
    # get the common indices
    I = np.intersect1d(I_x, I_y)
    discounted_similarity = pearson_corr(table, x, y) * np.min([1, len(I)/beta])
    return discounted_similarity

In [228]:
DiscountedSim(table_2_1, 0, 2, 2)

np.float64(0.8944271909999159)

#### 2.3.1.2 Variants of the Prediction Function

We can also use the standard deviation to effectively obtain a (residualized) regression function that uses the z-Scores to predict a user's rating. Effectively, we turn every observed rating into a z-score (demeaned and standardized by SD) of a user, then use for prediction the mean and SD of a user we already know and then use the correlation-function together with the z-score of the same item for other similar users, downweighting by the sum of absolute values of the pearson correlation coefficients:

$ \hat{r}_{uj} = \mu_u + \sigma_u \frac{\sum_{\nu \in P_{u}(j)} Sim(u,v) \cdot z_{\nu j}}{\sum_{\nu \in P_{u}(j)} |Sim(u,v)|} $

In [229]:
def sd_function(table, x: int):
    # x is the row of table on which to perform computation
    # get I_x
    I_x = np.where(np.isnan(table[x]) == False)[0]
    # get the mean of x
    x_mean = np.mean(table[x][I_x])
    # get the standard deviation
    sd = np.sqrt(np.sum((table[x][I_x] - x_mean)**2)/(len(I_x)-1))
    return sd

In [230]:
def sd_vector(table):
    # compute the standard deviation for each row
    sd_vector = np.zeros(table.shape[0])
    for i in range(table.shape[0]):
        sd_vector[i] = sd_function(table, i)
    return sd_vector

In [231]:
def normalize_table(table):
    table_copy = table.copy()
    for i in range(table.shape[0]):
        I = np.where(np.isnan(table[i]) == False)[0]
        table_copy[i][I] = (table[i][I] - np.mean(table[i][I]))/sd_function(table, i)
    return table_copy

In [232]:
def z_score_imputation(table, threshold, dimension: int = 0):
    # x is the row to be imputed
    # y is the list of rows to be used for imputation
    # create a normalized copy of the table
    table_copy = table.copy()
    normalized_table = normalize_table(table)
    # compute user sd
    sd_vector_store = sd_vector(table)
    # compute correlation matrix
    corr_matrix = corr_matrix_func(table, dimension)
    # compute means
    user_mean = mean_compute(table, dimension)
    # for each row in correlation matrix compute the k based on threshold
    k = [[] for _ in range(corr_matrix.shape[0])]
    for i in range(corr_matrix.shape[0]):
        k[i] = np.where((corr_matrix[i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(corr_matrix.shape[0]):
        k[i] = np.setdiff1d(k[i], i)
    # for each row and column in the table, compute the imputation
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            if np.isnan(table[i,j]):
                table_copy[i,j] = user_mean[i] + sd_vector_store[i]*np.sum(corr_matrix[i][k[i]]*normalized_table[k[i],j])/np.sum(np.abs(corr_matrix[i][k[i]]))
    return table_copy, corr_matrix, user_mean, k

In [233]:
table_copy, corr_mat, user_means, k_imputed = z_score_imputation(table_2_1, 0.7, 0)

In [234]:
table_copy

array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        , 6.37893144, 4.        , 3.        ,
        4.        ],
       [3.04146466, 3.        , 3.        , 1.        , 1.        ,
        1.10483034],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        , 1.52326871, 1.        , 2.        , 3.        ,
        3.        ]])

#### 2.3.1.4 Impact of the long tail

As discussed in the book, similarity weighting can be beneficial if, for example, some items are more often rated than others. For example, we might multiply by the logarithm of the ratio of number of all users to number of users who rated a specific item:

$w_k = \log\Big(\frac{m}{m_k}\Big)$

$ WeightedPearson(u,v) = \frac{\sum_{k \in I_{u} \cap I_{v}} w_k \cdot (r_{uk}- \mu_{u}) \cdot (r_{uk}- \mu_{u}) }{\sqrt{\sum_{k \in I_{u}\cap I_{v}} w_k \cdot (r_{uk}- \mu_{u})^2} \cdot \sqrt{\sum_{k \in I_{u}\cap I_{v}} w_k \cdot (r_{vk}- \mu_{v})^2}} $

In [235]:
# weighted pearson-correlation-matrix
def weighted_pearson(table_input, x: int, y:int, dimension: int = 0):
    table = table_input.copy()
    if dimension == 1:
        table = table.T
    # compute the correlation matrix
    m = table.shape[0]
    weights_pre = [len(np.where(np.isnan(table.T[i]) == False)[0]) for i in range(table.shape[1])]
    weights = np.array([np.log(m/weights_pre[i]) for i in range(table.shape[1])])
    I_x = np.where(np.isnan(table[x]) == False)[0]
    I_y = np.where(np.isnan(table[y]) == False)[0]
    # get the common indices
    I = np.intersect1d(I_x, I_y)
    # get the mean of x and y
    x_mean = np.mean(table[x][I])
    y_mean = np.mean(table[y][I])
    # get the numerator
    numerator = np.sum(weights[I]*(table[x][I] - x_mean)*(table[y][I] - y_mean))
    # get the denominator
    denominator = np.sqrt(np.sum(weights[I] * (table[x][I] - x_mean)**2)*np.sum(weights[I]*(table[y][I] - y_mean)**2))
    # get the correlation
    corr = numerator/denominator
    return corr
    

In [236]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

In [237]:
weighted_pearson(table_2_1, 0, 3)

np.float64(-0.9296696802013684)

In [238]:
def weighted_pearson_corr_mat(table, dimension: int = 0):
    if dimension == 0:
        number = table.shape[dimension]
        corr_matrix = np.zeros((number, number))
        for i in range(number):
            for j in range(number):
                corr_matrix[i,j] = weighted_pearson(table, i, j)
    elif dimension == 1:
        number = table.shape[dimension]
        corr_matrix = np.zeros((number, number))
        table = table.T
        for i in range(number):
            for j in range(number):
                corr_matrix[i,j] = weighted_pearson(table, i, j)
    else:
        print("Invalid dimension")
        return None
    return corr_matrix

In [239]:
table_2_1.shape

(5, 6)

In [240]:
weighted_pearson_mat = weighted_pearson_corr_mat(table_2_1, 0)
weighted_pearson_mat

array([[ 1.        ,  0.80428683,  0.89442719, -0.92966968, -0.99811498],
       [ 0.80428683,  1.        ,  1.        , -0.75028028, -0.92163538],
       [ 0.89442719,  1.        ,  1.        , -1.        , -1.        ],
       [-0.92966968, -0.75028028, -1.        ,  1.        ,  0.94087507],
       [-0.99811498, -0.92163538, -1.        ,  0.94087507,  1.        ]])

## 2.3.2 Item-Based Neighbourhood Models

As described in the book, all of the previously given models were user-centric, i.e. we compared two users in their ratings over all products. For this, we computed the set of relevant products for each user-pair and weighted the rating of another user with an appropriate similarity-measure, e.g. the Pearson-Correlation-Coefficient or Cosine-Similarity.
For Item-Based-Methods, we go the other way: we compare items in their similarity and then multiply the ratings of *the same* user for other items multiplied with their similarity for an item at hand. That means if we want to predict how much a user will enjoy a particular brand of car tires, we first compute how similar other items, e.g. windshield wipers, motors, car seats, are to tires, and then predict the user's rating for these car tires as a weighted sum of his ratings for all these other items. 
In contrast, with user-based methods we weight the ratings of *other users* for the *same item* with the similarity between the two *users*. 

$ AdjustedCosine(i,j) = \frac{\sum_{u \in U_i \cap U_j} s_{ui} \cdot s_{uj}}{\sqrt{\sum_{u \in U_i \cap U_j} s_{ui}^2} \cdot \sqrt{\sum_{u \in U_i \cap U_j} s_{ui}^2}} $

where $s_{uj}$ is the demeaned rating of user $u$ for item $j$.

In [241]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

In [242]:
i = 0
np.where(np.isnan(table_2_1[:,5]) == False)[0]

array([0, 1, 3, 4])

In [243]:
def AdjustedCosine(table, i: int, j: int):
    # i and j are the columns of table on which to perform computation
    # get U_i and U_j
    U_i = np.where(np.isnan(table[:,i]) == False)[0]
    U_j = np.where(np.isnan(table[:,j]) == False)[0]
    # get the common indices
    U = np.intersect1d(U_i, U_j)
    # get the mean of x and y
    i_mean = np.mean(table[U,i])
    j_mean = np.mean(table[U,j])
    # get the numerator
    numerator = np.sum((table[U,i] - i_mean)*(table[U,j] - j_mean))
    # get the denominator
    denominator = np.sqrt(np.sum((table[U,i] - i_mean)**2)*np.sum((table[U,j] - j_mean)**2))
    # get the correlation
    corr = numerator/denominator
    return corr

In [244]:
AdjustedCosine(table_2_1, 0, 3)

np.float64(0.8971499589146108)

Having computed the adjusted Cosine, let's use it to predict ratings. In order to do that we need to get the top-k-similar items. We can set k as we wish.

In [245]:
def TopKSimilarities(table, u: int, t: int, k: int = 3):
    # compute the top-k adjusted Cosine similarities for user u and item t:
    # get the number of items
    m = table.shape[1]
    # get the similarities
    similarities = np.zeros(m)
    for i in range(m):
        similarities[i] = AdjustedCosine(table, t, i)
    # eliminate the similarity of t with itself
    similarities[t] = 0
    # get the top-k similarities
    top_k = np.argsort(similarities)[-k:]
    return top_k, similarities[top_k]

TopKSimilarities(table_2_1, 0, 3, 3)

(array([4, 5, 0]), array([0.81348922, 0.87038828, 0.89714996]))

In [246]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

In [247]:
def AdjCosPrediction(table, u: int, t: int, k: int = 3, threshold: float = 0.7):
    # compute the prediction for user u and item t using the top-k adjusted Cosine similarities
    top_k, similarities = TopKSimilarities(table, u, t, k)
    # keep only the similarities above the threshold
    top_k = top_k[np.where(similarities > threshold)]
    similarities = similarities[np.where(similarities > threshold)]
    # get the mean of the user
    user_mean = np.mean(table[u][np.where(np.isnan(table[u]) == False)[0]])
    # get the prediction
    prediction = user_mean + np.sum(similarities*(table[u][top_k] - np.mean(table[u][np.where(np.isnan(table[u]) == False)[0]])))/np.sum(np.abs(similarities))
    return prediction

In [248]:
AdjCosPrediction(table_2_1, 0, 3, 3, 0.7)

np.float64(5.357962731499528)

In [249]:
# Create an imputation function that takes as input a table and returns the imputed table where the imputation is done using the top-k adjusted cosine similarity if an entry is missing
def AdjCosImputation(table, k: int = 3, threshold: float = 0.7):
    # create a copy of the table
    table_copy = table.copy()
    # for each row and column in the table, compute the imputation
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            if np.isnan(table[i,j]):
                table_copy[i,j] = AdjCosPrediction(table, i, j, k, threshold)
    return table_copy

In [250]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

Let us replicate the computation on p. 41:

In [251]:
table_2_1_adj_cosine_imputed_items = AdjCosImputation(table_2_1, 2, 0.7)
table_2_1_adj_cosine_imputed_items

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\229472857.py:16: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        , 6.50271747, 4.        , 3.        ,
        4.        ],
       [3.        , 3.        , 3.        , 1.        , 1.        ,
        1.        ],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        , 1.        , 1.        , 2.        , 3.        ,
        3.        ]])

# 2.3.6 A unified view of user-based and item-based methods

As described on p.45, one can also combine user-based-methods with item-based methods. In the following, I will present a method to impute missing values using pearson-correlation-coefficient between rows and between columns separately and weighting the imputations with the pearson-correlation.

In [252]:
def GeneralizedImputation(table, threshold):
    table_copy = table.copy()
    # compute correlation_matrix
    user_corr_matrix = corr_matrix_func(table_copy, dimension=0)
    item_corr_matrix = corr_matrix_func(table_copy, dimension=1)
    # compute means
    user_mean = mean_compute(table_copy, dimension=0)
    sd_vector_store = sd_vector(table_copy)
    # demean the table
    table_copy_dm = normalize_table(table_copy)
    # for each row in correlation matrix compute the k based on threshold
    k = [[] for _ in range(user_corr_matrix.shape[0])]
    for i in range(user_corr_matrix.shape[0]):
        k[i] = np.where((user_corr_matrix[i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(user_corr_matrix.shape[0]):
        k[i] = np.setdiff1d(k[i], i)
    # for each column in correlation matrix compute the k based on threshold
    k_cols = [[] for _ in range(item_corr_matrix.shape[1])]
    for i in range(item_corr_matrix.shape[1]):
        k_cols[i] = np.where((item_corr_matrix[:,i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(item_corr_matrix.shape[1]):
        k_cols[i] = np.setdiff1d(k_cols[i], i)
    # for each row and column in the table, perform imputation as follows
    # r_ij = user_mean[i] + sd_vector_store[i]*weighted_rating if table[i,j] is missing
    # weighted_rating = sum(user_corr_matrix[i][k[i]]*table_copy_dm[k[i],j])/sum(np.abs(user_corr_matrix[i][k[i]])) * (sum(np.abs(user_corr_matrix[i][k[i]])) / (sum(np.abs(user_corr_matrix[i][k[i]])) + sum(np.abs(item_corr_matrix[j][k_cols[j]]))) + sum(item_corr_matrix[j][k_cols[j]]*table_copy_dm[i,k_cols[j]])/sum(np.abs(item_corr_matrix[j][k_cols[j]]))
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            if np.isnan(table[i,j]):
                weighted_rating = np.sum(user_corr_matrix[i][k[i]]*table_copy_dm[k[i],j])/np.sum(np.abs(user_corr_matrix[i][k[i]])) * (np.sum(np.abs(user_corr_matrix[i][k[i]])) / (np.sum(np.abs(user_corr_matrix[i][k[i]])) + np.sum(np.abs(item_corr_matrix[j][k_cols[j]])))) + np.sum(item_corr_matrix[j][k_cols[j]]*table_copy_dm[i,k_cols[j]])/np.sum(np.abs(item_corr_matrix[j][k_cols[j]])) * (np.sum(np.abs(item_corr_matrix[j][k_cols[j]])) / (np.sum(np.abs(user_corr_matrix[i][k[i]])) + np.sum(np.abs(item_corr_matrix[j][k_cols[j]]))))
                table_copy[i,j] = user_mean[i] + sd_vector_store[i]*weighted_rating
    return table_copy, corr_matrix, user_mean, k

In [253]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

In [254]:
table_2_1_gen_imputed, corr_matrix_gen, user_mean_gen, k_gen = GeneralizedImputation(table_2_1, 0.7)
table_2_1_gen_imputed

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\2376229201.py:16: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


array([[7.        , 6.        , 7.        , 4.        , 5.        ,
        4.        ],
       [6.        , 7.        , 6.44573888, 4.        , 3.        ,
        4.        ],
       [2.63396979, 3.        , 3.        , 1.        , 1.        ,
        1.07147565],
       [1.        , 2.        , 2.        , 3.        , 3.        ,
        4.        ],
       [1.        , 1.16295641, 1.        , 2.        , 3.        ,
        3.        ]])

We have imputed the rating in the following fashion:

$ \hat{r}_{ij} = \mu_i + \sigma_i \cdot \Big[ \frac{\sum_{\nu \in P_u(j)} Sim(u, \nu) \cdot z_{\nu j}}{\sum_{\nu \in P_u(j)} |Sim(u,v)|}\cdot\frac{\sum_{\nu \in P_u(j)} |Sim(u,v)|}{\sum_{\nu \in P_u(j)} |Sim(u,v)| + \sum_{t \in Q_j(i)} |ItemSim(j, t)|} + 
\frac{\sum_{t \in Q_j(i)} ItemSim(j, t) \cdot z_{i,t}}{\sum_{t \in Q_j(i)} |ItemSim(j, t)|} \cdot\frac{\sum_{t \in Q_j(i)} |ItemSim(j, t)|}{\sum_{\nu \in P_u(j)} |Sim(u,v)| + \sum_{t \in Q_j(i)} |ItemSim(j, t)|} \Big]$

where

$ \sigma_u = \sqrt{\frac{\sum_{j \in I_u} (r_{uj} - \mu_u)^2}{|I_u| - 1}} $ is the standard deviation for user *u*,

$ z_{uj} = \frac{r_{uj} - \mu_u}{\sigma_u} = \frac{s_{uj}}{\sigma_u}$ is the z-score of item *j* for user *u*, and 

$ Sim(u,v) $ is the Pearson-Correlation on user-level and $ ItemSim(j,t) $ is the Pearson-Correlation on item-level.

### Note:

This imputation procedure is not given verbatim in Aggarwal (2016) but is my interpretation of the description on p. 45. He effectively describes taking a weighted average of the prediction from the user-based-method and the item-based-method. The most straightforward weights that fulfill the requirements in "2." are the ones that I have used above: linear weights. However, nothing prevents the interested reader from implementing a different weighting scheme; for example one that is non-linear. A harmonic or geometric mean are just as possible as the arithmetic mean that I have given above. Similarly, one can also implement this method using as a similarity-measure the Adjusted Cosine. The way to implement that would be to create an AdjustedCosine-Similarity-Matrix just as one constructs the correlation-matrix, once on user-level, once on item-level, and then use those similarities. For example:

In [255]:
def AdjustedCosineComputation(table, i: int, j: int, dimension: int = 1):
    # i and j are the columns of table on which to perform computation
    # get U_i and U_j
    table_copy = table.copy()
    if dimension == 0:
        table_copy = table_copy.T
    U_i = np.where(np.isnan(table_copy[:,i]) == False)[0]
    U_j = np.where(np.isnan(table_copy[:,j]) == False)[0]
    # get the common indices
    U = np.intersect1d(U_i, U_j)
    # get the mean of x and y
    i_mean = np.mean(table_copy[U,i])
    j_mean = np.mean(table_copy[U,j])
    # get the numerator
    numerator = np.sum((table_copy[U,i] - i_mean)*(table_copy[U,j] - j_mean))
    # get the denominator
    denominator = np.sqrt(np.sum((table_copy[U,i] - i_mean)**2)*np.sum((table_copy[U,j] - j_mean)**2))
    # get the correlation
    corr = numerator/denominator
    return corr

In [256]:
def AdjustedCosineSimilarityMatrix(table, dimension: int = 0):
    # compute the adjusted cosine similarity matrix
    m = table.shape[dimension]
    adj_cos_sim_matrix = np.zeros((m,m))
    for i in range(m):
        for j in range(m):
            adj_cos_sim_matrix[i,j] = AdjustedCosineComputation(table, i, j, dimension = dimension)
    return adj_cos_sim_matrix

In [257]:
adj_cos_sim_matrix_users = AdjustedCosineSimilarityMatrix(table_2_1, 0)
adj_cos_sim_matrix_items = AdjustedCosineSimilarityMatrix(table_2_1, 1)
adj_cos_sim_matrix_users, adj_cos_sim_matrix_items

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\3055660411.py:19: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


(array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
        [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
        [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
        [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
        [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]]),
 array([[1.        , 0.94063416, 0.98782916, 0.89714996, 0.67675297,
         0.57263713],
        [0.94063416, 1.        , 0.99862543, 0.69310328, 0.51449576,
                nan],
        [0.98782916, 0.99862543, 1.        , 0.6381449 , 0.62092042,
         0.62861856],
        [0.89714996, 0.69310328, 0.6381449 , 1.        , 0.81348922,
         0.87038828],
        [0.67675297, 0.51449576, 0.62092042, 0.81348922, 1.        ,
         0.33333333],
        [0.57263713,        nan, 0.62861856, 0.87038828, 0.33333333,
         1.        ]]))

Next we can rewrite our imputation function to use either the Adjusted-Cosine-Similarity or the Pearson-Correlation-Coefficient:

In [258]:
def GeneralizedImputationFlexible(table, threshold, imputation_method: str = "pearson"):
    table_copy = table.copy()
    if imputation_method == "pearson":
        user_corr_matrix = corr_matrix_func(table_copy, dimension=0)
        item_corr_matrix = corr_matrix_func(table_copy, dimension=1)
    elif imputation_method == "adjusted_cosine":
        user_corr_matrix = AdjustedCosineSimilarityMatrix(table, dimension=0)
        item_corr_matrix = AdjustedCosineSimilarityMatrix(table, dimension=1)
    else:
        print("Invalid imputation method")
        raise ValueError
    # compute means
    user_mean = mean_compute(table_copy, dimension=0)
    sd_vector_store = sd_vector(table_copy)
    # demean the table
    table_copy_dm = normalize_table(table_copy)
    # for each row in correlation matrix compute the k based on threshold
    k = [[] for _ in range(user_corr_matrix.shape[0])]
    for i in range(user_corr_matrix.shape[0]):
        k[i] = np.where((user_corr_matrix[i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(user_corr_matrix.shape[0]):
        k[i] = np.setdiff1d(k[i], i)
    # for each column in correlation matrix compute the k based on threshold
    k_cols = [[] for _ in range(item_corr_matrix.shape[1])]
    for i in range(item_corr_matrix.shape[1]):
        k_cols[i] = np.where((item_corr_matrix[:,i] > threshold))[0]
    # for each value of k, remove the same number if it is in k, e.g. remove 2 from k[2]
    for i in range(item_corr_matrix.shape[1]):
        k_cols[i] = np.setdiff1d(k_cols[i], i)
    # for each row and column in the table, perform imputation as follows
    # r_ij = user_mean[i] + sd_vector_store[i]*weighted_rating if table[i,j] is missing
    # weighted_rating = sum(user_corr_matrix[i][k[i]]*table_copy_dm[k[i],j])/sum(np.abs(user_corr_matrix[i][k[i]])) * (sum(np.abs(user_corr_matrix[i][k[i]])) / (sum(np.abs(user_corr_matrix[i][k[i]])) + sum(np.abs(item_corr_matrix[j][k_cols[j]]))) + sum(item_corr_matrix[j][k_cols[j]]*table_copy_dm[i,k_cols[j]])/sum(np.abs(item_corr_matrix[j][k_cols[j]]))
    for i in range(table.shape[0]):
        for j in range(table.shape[1]):
            if np.isnan(table[i,j]):
                weighted_rating = np.sum(user_corr_matrix[i][k[i]]*table_copy_dm[k[i],j])/np.sum(np.abs(user_corr_matrix[i][k[i]])) * (np.sum(np.abs(user_corr_matrix[i][k[i]])) / (np.sum(np.abs(user_corr_matrix[i][k[i]])) + np.sum(np.abs(item_corr_matrix[j][k_cols[j]])))) + np.sum(item_corr_matrix[j][k_cols[j]]*table_copy_dm[i,k_cols[j]])/np.sum(np.abs(item_corr_matrix[j][k_cols[j]])) * (np.sum(np.abs(item_corr_matrix[j][k_cols[j]])) / (np.sum(np.abs(user_corr_matrix[i][k[i]])) + np.sum(np.abs(item_corr_matrix[j][k_cols[j]]))))
                table_copy[i,j] = user_mean[i] + sd_vector_store[i]*weighted_rating
    return table_copy, corr_matrix, user_mean, k

In [259]:
pearson_table_2_1_gen_imputed, pearson_corr_matrix_gen, pearson_user_mean_gen, pearson_k_gen = GeneralizedImputationFlexible(table_2_1, 0.7, imputation_method = "pearson")
cosine_table_2_1_gen_imputed, cosine_corr_matrix_gen, cosine_user_mean_gen, cosine_k_gen = GeneralizedImputationFlexible(table_2_1, 0.7, imputation_method = "adjusted_cosine")

pearson_table_2_1_gen_imputed, cosine_table_2_1_gen_imputed

C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\2376229201.py:16: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator
C:\Users\maggo\AppData\Local\Temp\ipykernel_12308\3055660411.py:19: RuntimeWarning: invalid value encountered in scalar divide
  corr = numerator/denominator


(array([[7.        , 6.        , 7.        , 4.        , 5.        ,
         4.        ],
        [6.        , 7.        , 6.44573888, 4.        , 3.        ,
         4.        ],
        [2.63396979, 3.        , 3.        , 1.        , 1.        ,
         1.07147565],
        [1.        , 2.        , 2.        , 3.        , 3.        ,
         4.        ],
        [1.        , 1.16295641, 1.        , 2.        , 3.        ,
         3.        ]]),
 array([[7.        , 6.        , 7.        , 4.        , 5.        ,
         4.        ],
        [6.        , 7.        , 6.44573888, 4.        , 3.        ,
         4.        ],
        [2.63396979, 3.        , 3.        , 1.        , 1.        ,
         1.07147565],
        [1.        , 2.        , 2.        , 3.        , 3.        ,
         4.        ],
        [1.        , 1.16295641, 1.        , 2.        , 3.        ,
         3.        ]]))

In [260]:
pearson_corr_matrix_gen, cosine_corr_matrix_gen

(array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
        [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
        [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
        [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
        [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]]),
 array([[ 1.        ,  0.72347804,  0.89442719, -0.8992288 , -0.82422559],
        [ 0.72347804,  1.        ,  0.97072534, -0.72057669, -0.8992288 ],
        [ 0.89442719,  0.97072534,  1.        , -1.        , -0.8660254 ],
        [-0.8992288 , -0.72057669, -1.        ,  1.        ,  0.87705802],
        [-0.82422559, -0.8992288 , -0.8660254 ,  0.87705802,  1.        ]]))

In [261]:
table_2_1

array([[ 7.,  6.,  7.,  4.,  5.,  4.],
       [ 6.,  7., nan,  4.,  3.,  4.],
       [nan,  3.,  3.,  1.,  1., nan],
       [ 1.,  2.,  2.,  3.,  3.,  4.],
       [ 1., nan,  1.,  2.,  3.,  3.]])

Are we surprised that these two outcomes are exactly identical? Not too much if we have read correctly footnote 3 on p. 44: Pearson Correlation coefficient is identical to the cosine coefficient for row-wise mean-centered matrices *if* the user-means have been computed using all observed entries (rather than just the mutually observed ones). This is true because in that case the Adjusted-Cosine-similarity that is presented on page 40 is equal to the Pearson-Correlation given at the beginning of this section. What Aggarwal does not mention is that this is *also* true if the user-mean is computed only for the mutually observable set for both Pearson and Adjusted-Cosine. That is because these formulas then boil down to the same mathematical foundations.
What Aggarwal (2016) rather means (I stipulate) is that the AdjustedCosine-similarity *as presented for items* boils down to the Pearson-Correlation-Coefficient *for items* if user-means are computed over the entire row. I am hence somewhat at a loss for what Aggarwal actually stipulates here. The mathematical identity of Adjusted-Cosine and Pearson-Correlation should be obvious given that mean-computation is performed in the same fashion. Where it differs is if you compute the similarity between items rather than between users. However, that is nothing new.

# 2.4 Other Neighborhood Methods

The rest of chapter 2 seems, to me, a high-level overview of other neighborhood-based methods that mainly foreshadow future chapters. As such, it is not fairly straightforward to implement such a diverse set of models if they return later in full length. Therefore, these methods are not coded up here but instead will be coded in the notebooks for the respective chapters.